name: CI
on: [push, pull_request]

jobs:
  spell-check:
    name: spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install misspell
        run: |
          curl -L -o ./install-misspell.sh https://git.io/misspell
          sh ./install-misspell.sh -b .
      - run: ./misspell -error README.md
